# Site settings
title: 黑色一眸
email: gmail for jobinson99
description: "黑色的不是眼睛而是眼圈"
baseurl: ""
url: "http://jobinson99.ga"

# Build settings
markdown: kramdown
permalink: pretty
relative_permalinks: true

future: true

# 分页


# 语法高亮
highlighter: pygments

include:
- .nojekyll

# 样式选择
themes: /themes/atlas
